name: Bug Report
description: Report an issue to help us improve Edelweiss
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: Edelweiss Version
      description: Which version of Edelweiss are you using?
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System Version
      description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
      placeholder: e.g. Windows 10 21H1, macOS Catalina 10.15.7, or Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets/Logs
      description: |
        A list of assets (logs, screenshots, etc) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
        required: true
